apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: prod
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:rKzbjISCtwPOwiQ=,iv:aStPNYVSy7KtruDGuV0ITqeQWLS7oahOXUuIZRrWsA8=,tag:Ys5uzVaR0yu4tH0Lpk4GyA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:/hnqtndXIHQPkXQ=,iv:aHyvzIhhQzS7TiM97k/hs9Z+z//Ydj3v8lOX5C/g/E4=,tag:+iHX1Ufffe2bQNGuPy56aQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:3v1LTwrl/m6JS34=,iv:eCYIDDEseqjFcDznqP7KevdcKXxO2DD6yZA0UWaGnVo=,tag:u1d8q98BKYMxnAieZlrtRA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:9Aw2w+VXDaNjC788Z68R,iv:2Qmee8gwP0Nu4sxFgOsMxCsmBiGLtQErx/95siU2Lls=,tag:oi8U/H0NO0UWdll9Wek1EQ==,type:str]
    API_PORT: ENC[AES256_GCM,data:DJcwHcp5j8QS1aTN,iv:H9mQSGFlc4ZDlNTxhYZEjT3VWS6soYWuARjk47NtaOs=,tag:YNQw41xuuLZZcPfecfF1RQ==,type:str]
    GITHUB_PROJECT_NUMBER: ENC[AES256_GCM,data:x30/6Do6oFNxE6/Av66do1z8O2TNA8N0sw==,iv:K7bxoo+FgGp57KEp+QqyCpTL4Kn8jfL6UBhOEnsPjZU=,tag:yPJDMR2A7ftk0P2H9c5RSw==,type:str]
    GITHUB_REPO: ENC[AES256_GCM,data:0LaQcjaex7Ppc71nMW6P,iv:YkmE+uS2MfbrRkcm0MeUn8fHbgvB9xMyFt1DwkxoRYo=,tag:+TvyUpopsNnFS/IIlYVUmg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:0GJZGxAiaWuNxfcVu8NWnQ==,iv:8+ZZ/YghlkrISKBDrIQC4OxaFbOtaIvl/QfFXOd5R0E=,tag:CDYHsxGMlKz8UUlB245fiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Vzc5ZENObW5xZjZ6bkdQ
            ZDFpNHNMMnVqRVE5ckl4Q1Fuc3BRU3RYZW5NCjQ4N29jMGtaTFhSZFNJMFI1M2VG
            M0RrdGhURnl5Z210K1dUQ3BCSm81ZXMKLS0tIFhXcVM3alpnZWQ3MlRzeGY5aWJu
            STh6Y29ETGJQS1JZN0tkOGZFYmUyN1kKu8I512qVxqShdlYx2gSg0te+yRP0Ej30
            7NR8Ali2AwMSMT7dcKJ7N77+xro2w8yA2VqUJI1c11XpLHk3uiYZYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T05:02:02Z"
    mac: ENC[AES256_GCM,data:ZmZaSh7YbfFbPUNZAhDog4OVwYgx0nTNEJEcMb7QDEJnIYbRL4NS9JQUdztfdYu0o6pPj9hiVEeupFoN7KdzDWbu9bC5T+8nQK5w9vhEOEWZyLxWYloC6us9lNC/1x2b2j5uxDnJ5Gt8ob3y62F0RGM6SZb1RiZFO2Ynkvi3jgk=,iv:yFPveNAGwghdqszZvPLHOsNNO0mFK7LkdXXRat5gdfg=,tag:uZptjJ+PGeketR/tvNevUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
