apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: prod
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:tsYK3+pTIsTU,iv:GVa/WfoE4N3R8g7pzQR0VZcB4YyJd7zwefNrJlA6MOw=,tag:HIWUlZkMcbgF7rQAVI6j1Q==,type:str]
    DB_NAME: ENC[AES256_GCM,data:zRLr7auU,iv:S973SLeElQ0aTrevAj+boJ2pjVrBSyFoHm02E8P5R90=,tag:izX5ZM0MvjT8yC7LkXhRuA==,type:str]
    DB_USER: ENC[AES256_GCM,data:jOMMiQVkdrmDYaI=,iv:aUsNzkweLFsq5GLDmmx5A9HX5edMDSWVYlSO2hEb9Wo=,tag:nrQQw/64erepf5vrgtP6hA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:5DLqtOfM/heJia+lIxBhpQ83,iv:OF0k93qb6JT76E+Sp90qpx1+WM4yd/TZkjNDIeepFZQ=,tag:IZroMPJIK6F2lqy5h4N19Q==,type:str]
    API_PORT: ENC[AES256_GCM,data:a/D7pw==,iv:Ye2EDV3ItRAGNR/nePgckSD0bZXL7KEkDRxdFXzqrfY=,tag:fwIf8ENEw//d+NonoMIqKw==,type:str]
    GITHUB_PROJECT_NUMBER: ENC[AES256_GCM,data:WQ==,iv:kgHE7HuF9PWkqReTEXb5Z3pvyhFTOJ5f/B2FXLJqiLI=,tag:iNipLxzWKvp2wTIpSQ9McQ==,type:str]
    GITHUB_REPO: ENC[AES256_GCM,data:fB3cT9IHQCtkhHxT8CvuViyCG3//z4UwajTA+DkmlKzzPZ6Hdn8XTTMaKDjh,iv:Ekdzbfis47bsUgjwGjv6eFqUwc1Y/PbV9cJQULm/KUs=,tag:mhsWQ35vho+TXrboWinO1A==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:r3GYCsUPhzGMI0PznpLBaizN6CDoiPK3H5UEc8LfIkf3wEOJScHlTA==,iv:anvVHeGnpmupxXEC6rjO8P+nC3cKcXisrfjkQOrsu2c=,tag:hpTYgotLXRfm1r84ZrLb3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeG5sQ0JZNmZiU0Y5WWhh
            dnVhUlh1MUNQaEo1Z0xhWkFKNjB6VFpoVWhvCnA4V2RCa1JrcWtZVzdqMUc2aVJ1
            NGZzOTY4TlRFYTVDWUZGOWlBMG50T2MKLS0tIGl3MHVoSmZsZkNQMjZZV3RMcWFm
            MElZQWE1K1hqUHk2MkV4Mmlmd3ZZNWcK9oC+lXMH+Et8TE5Gbqc1SUTQ9Ns2xst7
            3T4WAln4UUAzukao6F9AHy0nUBGq+dJRdhJpr7jqSwkDZ+u2IxNkLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T18:27:21Z"
    mac: ENC[AES256_GCM,data:gSfr5ApZ8cNk5P9KSPe/Ufrj/cev8QPdQuhQHZq4lZ4Zm7kBjKMkaa7IZ4bm5bOyScFw7uTtGxJUysroCRCcW6lgGAEJUo03HzB9hXtdEfZ4RGuhfdmwe3HP7egKuE17uaJVy9KNTLfKi1N8QPMJC4INvF1qi7E2sTjgj22QYHU=,iv:DdDjtk8HWpuEakY+j1xYebql4J7DfG8qSuf7BfzfWBQ=,tag:d0yv40zzAdePt6K7N79JvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
