apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: prod
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:4JP09JL2spc=,iv:vDtuku+MmYb0n2z7+U0uLPcAScH6l3P5Do/XoJauwQE=,tag:n7chWIjYlVGEjj5j8Jl4wg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:R7I496E8,iv:jSuRnXOd0gcs/1Lvcp69mzcLTyg27BwbPYMMncJHet0=,tag:aThzZqyagB2ymmX9GdTPwg==,type:str]
    DB_USER: ENC[AES256_GCM,data:sy3mIT2lc7PkOUY=,iv:MnGOMYNUOGmSJnaXoLLtcSFEQAW+QkvJwWAk8lNnk/M=,tag:yIo1zA7X/t2pqBrOqDRuwA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:vVWJL1CUsCcW1CxGKVWBTD98,iv:fESqm6eklVtjNFW1TZll/muYGbfQuzquJvudYbIKkcU=,tag:vrSc+nFkg/rhIp3cCmVduw==,type:str]
    PORT: ENC[AES256_GCM,data:B8WlNA==,iv:plsYta1PSGqR8XhQPCJ1ruYB1W00HU9vpA4m8TH/mLE=,tag:Fmt6f8/rvssXA61K5oMj6A==,type:str]
    GITHUB_PROJECT_NUMBER: ENC[AES256_GCM,data:kQ==,iv:mGjMe5wU7SLOdHodQ1dfYPRz4YoMaHfUUOPLdju1hqU=,tag:u7KwaOoXRvS9v2cSaY8Jog==,type:str]
    GITHUB_REPO: ENC[AES256_GCM,data:OUzKLNLDjEb1IdSUmmo68xLPKCvyrtQV+MUW5XuEzJHCGgqJtYfCQ7uo8Vhq,iv:LsxCbvTnlz/+LyRKL9lN6//fNlrnixmYex0JQ6TtxrY=,tag:OGdl+zmYOsxN5gkRU7Elxg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:xl/OtOpfGdirbomskFikyAKvBZonlugvaG9ut4pQZCTXhsvd6Ad/Rg==,iv:Nij9ppA3wEqlGF0o1Vi0VIGLajY0CLv486x3P12BTZc=,tag:5jXPeM5QmHJrxvh4a1EShw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSkljVG1NeDByRUd6c0Zv
            eGllajBrSWNuYUhLaVAwNU40dHBLNXFHZnk4CnB2OGhOOGdWY1BRZmNaNHQ0cEQ4
            QWJ5Rlo4MTZYQXp0Uy9xRXZmUXBFWEEKLS0tIEk1ekU1c3Y5QVVBR2ZuZCtZMXFm
            NGNNdjhBWkVyQVlnTTBJaTkyQkVpVkUKnr0KnEd3dqI6zq8yVcApjALzCLOxUiZS
            gvcyvwJkMQreQ76uPFlRxKTxafqD+PtDN0DsIh7ZXX7hgE9WWhSVCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T19:33:37Z"
    mac: ENC[AES256_GCM,data:JrYEtVMuyV3VD6uW2/21pphPnaLcz8bO8uPk0cCrDrMURT0ZL3CmS9MP8o2dGeGYUDH1lA06TSoS3D5EUtCvMfEx3BmFadymjz0V0kDW2NzDibj9ftvODptmNhxeuIhXquZgtwfnCcdtNT1Je4K+Ycw6v9+ouUlXFDHL3nQDBf4=,iv:u1b06xLcFDIa9JP2hrqWYXfHwG8ka4EbXeYh7lqK5po=,tag:JB6XEmECWNQ/Bza8xgGaAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
