apiVersion: ENC[AES256_GCM,data:4Ig=,iv:SBB76FdCsYCaTVvj3K9Cv34xSDCEryPeD1mH3G5tIt8=,tag:7GmLIseLn/PrxlsvQBBRwA==,type:str]
kind: ENC[AES256_GCM,data:dpiM77Lp,iv:nGRihP9hrv9PfEhdAe22gAeMxTAftocZCKzzep7yx+I=,tag:OPPzlxTw+y+31WAPTfrzOQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hRP03F1vIukxl9E=,iv:ZrjrJrzbBJuau/w+k52kjsgTgcutZnv/sidPvLjF76Q=,tag:rXJjGgrucVjnNJxBV7TCYw==,type:str]
    namespace: ENC[AES256_GCM,data:VgUBTw==,iv:LvVJ0cYJ8YjERGdY+fYMJewQQpobfnHnXZq5tWlLQYk=,tag:sfNem83U4PWpcx/X0hfYSw==,type:str]
type: ENC[AES256_GCM,data:nqFwZUaw,iv:M0DA8TeyEfiatQQybc/6WqRLZK22mLpB63tA/FdQNGw=,tag:+LvcPq4Xmsj/HJ8kboC75w==,type:str]
stringData:
    DB_HOST: ENC[AES256_GCM,data:NF15WKfo9WF2Zb4=,iv:+suMI8tS3cyUsArTkDOk62M5/c++s2+Q+JDOzqFOIuM=,tag:+3kp5ScJbFJzXOoqgBqf8w==,type:str]
    DB_NAME: ENC[AES256_GCM,data:4QZagM72yjA3KsY=,iv:tyvsH8RW1Eia0sRfKKa71eNZYtvtxx+zQT/mSOBebmU=,tag:o5IJRYdBgmMQD60L1feLBQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:foK8zDMcflIJX58=,iv:t2dvOpU+QFh4O8PQrILTbFhy/qbJdEd0olrJNys1wso=,tag:i77hGJXZYhIwj7b0G2uG2w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:aRnKLm2uazm+atsmJx9Y,iv:Z/c5YfSqDQPWcIRfAKBVV3rWnbXjiJNK08Rap/IqGPQ=,tag:nrw5ewPZmBjq7LBDEGtFQA==,type:str]
    API_PORT: ENC[AES256_GCM,data:+cwqW5AwGW82DLNf,iv:F2RtkO8NtcnIX2caFyVYmWSxn2CdYaCMp3sWwJ+9sag=,tag:qNHmvIC6XqAzJucKIPiImw==,type:str]
    GITHUB_PROJECT_NUMBER: ENC[AES256_GCM,data:vIPmdbkJA/hwPDjHx4c+ZBkFmp/J7RDY1w==,iv:1PrOImCP7qEqRNG0G1eA03oHYFAFzE4eZ73Yqq0cEb4=,tag:4XrUgCpCQaoo4Pv0dNZDhg==,type:str]
    GITHUB_REPO: ENC[AES256_GCM,data:xblA6R3iLr/z0flOI2Ai,iv:65Dkm4do9Ttd1EjDSLE6rUc6GQAu/p8iNJxaimDwapk=,tag:z+Ui3cv629/av0qOebMfUw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:ODYIneJjhPYCqlKKptBTKw==,iv:wb8TSOz4nigJZLYwcLVajtzQAVB+IMycbZR/UCWyHdQ=,tag:qmKEEM5ve8Tkqn66bFbDzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobld2TjFZSlUrdkpTOCtY
            WnZYdEtnbVlPRkg4TWM0Ty9uRDVNUlRCRkRFCklKMHRMKzJPUnZ1Y2FqVUVHVkdk
            MjIzL1hkM2JSN3pMbjBua1hXRXVnMlUKLS0tIERuOUZGN01ZcXhNcEhnVjJwdWgy
            a1dUUVBIeW8yblU0d3M2Yy9HTGhTQXcKsemnHyKcwj9/ObKIm+Vatmr+1zEh1KY9
            p+spIGXjstU6X0vvyN6IvD1Tkt+PeoXHlGxnu2Kii5Uv08d6cRb+uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-02T05:18:38Z"
    mac: ENC[AES256_GCM,data:73Qb70SoF64nIlwtwxfispxmaicpAIr02WSba6G3CATFHRg2OZqa6qDBFZWGbML3OEUTHGNuTJQz4HHOxa0FtOkMCvm7CwHluw6x8z0NSM190otvdOSj2ueq88wgq33k3YdITK+lFBdwQRFchTpTgB+aTy/yp/kvuirx5j1GUnU=,iv:T3P2AL61QuuWPUxMhXJbWekf+sDUFOWK5SL5chuMSgo=,tag:xmqJ/nH9I9ON1loO/wwlkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
