apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-stack
spec:
  replicas: 1
  selector: { matchLabels: { app: metrics-stack } }
  template:
    metadata: { labels: { app: metrics-stack } }
    spec:
      containers:
        - name: metrics
          image: docker.io/funnyadd/metrics-a25-grp1-eq10:DEBUG
          ports: [{ name: http-metrics, containerPort: 5001 }]
        - name: mobilitysoft
          image: docker.io/funnyadd/mobilitysoft:DEBUG
          ports: [{ name: http-mob, containerPort: 5002 }]
---
apiVersion: v1
kind: Service
metadata: { name: metrics }
spec:
  selector: { app: metrics-stack }
  ports: [{ name: http, port: 5001, targetPort: http-metrics }]
---
apiVersion: v1
kind: Service
metadata: { name: mobilitysoft }
spec:
  selector: { app: metrics-stack }
  ports: [{ name: http, port: 5002, targetPort: http-mob }]
