apiVersion: batch/v1
kind: CronJob
metadata:
  name: metrics-snapshot-job
spec:
  schedule: "*/5 * * * *"   # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl
              image: curlimages/curl:latest
              args:
                - -X
                - POST
                - "http://metrics:5001/api/kanban/snapshot?owner=log680-mtl-mobilitysoft&project_number=1"
