apiVersion: batch/v1
kind: CronJob
metadata:
  name: metrics-snapshot-job
spec:
  schedule: "*/1 * * * *"   # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: curl
              image: curlimages/curl:latest
              args:
                - -X
                - POST
                - "http://metrics:5001/api/kanban/snapshot"
