apiVersion: v1
kind: Secret
metadata:
    name: metrics-app-secrets
    namespace: staging
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:IIFzXAmNvr8=,iv:pRVzh+REySDdMa2EPh97juhVCTgjrvmM1yqN6qSt2Hw=,tag:10nBubRd3Z1jn/CKj2Rn+g==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Kf2jUiNcMO7TDUEBMuE=,iv:oldhjaIRBP5MCn3m0jX+GZbS4+fBLySxpsvSByMeBh4=,tag:id5jN2iv1Xc/+rj8mbbgsg==,type:str]
    DB_USER: ENC[AES256_GCM,data:I16v10fe9a/J6tI=,iv:jTOYgrGLbP2t362XZ3ZVExsEhfesDOprm+XLnBU9jjg=,tag:4orJVXLlaDEAuXNN8XzHRw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:JqSE7LZhkBByeEH8UQssFoEg,iv:q/xpwnY6SCMLnvcnx7bmAU7DFP/GxPpFAkY27PiOXmk=,tag:qsnRmYLOTygQkasmw8DE9Q==,type:str]
    PORT: ENC[AES256_GCM,data:awl4VA==,iv:j4dD2bjNFqsL4IJbPsl191h3N5UnC9LKBGkQv7O6w10=,tag:tdPmtG1cUBhnZvGWBe23Bw==,type:str]
    GITHUB_PROJECT_NUMBER: ENC[AES256_GCM,data:CA==,iv:GGFe+rCzNpuzUr6FDDKdyldu5ndDRQdhLCPGrIi6kl0=,tag:FdWwgGupzWDMMOJ22rPmPQ==,type:str]
    GITHUB_REPO: ENC[AES256_GCM,data:rRFejuU1+Wpesehj/Qo6oaTL6ymB+QEnVIpHRbA9eIvgBM141S+HCfaDbxXy,iv:1YO7XJbXVQoKmOrrz1pC2K19wl/YQBN4OhwEpAVnzow=,tag:fY8DYkO4JEFUDv9urFf7ZA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:VouoHFQyANAOZCfha/aHi9QUPlRuiFdrBs/uAT9mXNiLffbxquxj5g==,iv:npANB/lTMrKeggzapgjZUArcWsZa11IRi5MEoAkpo94=,tag:XkrpJX4E+6PbN1etkSvdLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYzRiNUdVaGpxbUQ1U1JH
            QUd5NjZsNm1hcHdHWWJ5dlM0ZzVUYW5uMzNnCmFuSTE0ajVybklJU1R5c1FydzdK
            Ymlud3BzSXdnK1pjcjhMcVBESmxUWHMKLS0tIGRSb1lsVi9oWnZwNlppTHJpZXd0
            Uk1MUTB5UGpIWXYzZzlqU1VaaWRXdmsKjEHaKRp7kKgXKQ8CUUhR1vH63hVlwbSX
            iLN4bDqNRVMYZDgpMrUxlEdK4mSYxyOMvwn/ia1Y0PnisPIc0Ob7jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T21:00:24Z"
    mac: ENC[AES256_GCM,data:0sn96Uxpj1HbF9W2yBRfpNPkkLbP2yr20BGeAvhnOMSzogMWNhmrwcZoSsA8MdvXoct7myT2c9kME7q2+SG6Qi8l1gDncqQKl6AFbax0ynxeW7vm/pTyBiwxnQC4HEcoBKqFGYOODiHPfwJJOZvdcjv9pmgoQjkqb/HFozYvZoA=,iv:R+umsMHZvMuWQLyxnRGjgrg93DgnkOfLy4WU8oGUTvY=,tag:C6fMJ1aVZQTTBiPSYSK1GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
