apiVersion: v1
kind: Secret
metadata:
    name: metrics-app-secrets
    namespace: staging
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:mkE5NylgJes=,iv:f+Q7KSjnijrlJndVl4JBg6nO4eHRPE2DAzJNwRrdeOU=,tag:lP2qyycBJ0CFZhkeVtHluw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:t28Fve1+OeWhaISHlhg=,iv:c6UQvZcOjf/IkPxz87pEspMZ6nTzJa+CzbJXtrzrvCg=,tag:PY02kAuW7XBisgo49ybmEA==,type:str]
    DB_USER: ENC[AES256_GCM,data:5fEyf1GN0q4qMoQ=,iv:KoQZWzGkRcYwSdWcJzz5BUPK7YvAXPkQb473EGckeyc=,tag:QRaI0Awh2JTn5fDjLx686Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ECUHkA3O+2t3dHCnBEPkd3wa,iv:WREi0ZaXOZV9wgcxyF3L3QZ9WjOQaIJqMEmVm7EcNK4=,tag:kBtUHdQTcqSjZJkkMg6FoQ==,type:str]
    PORT: ENC[AES256_GCM,data:g0FqqQ==,iv:jrSBj2iXyxA4M14bXcyhOyS0eEppSH0jvTzauCNJq9w=,tag:6pR6cMY1lJ9IQqpINSBrOw==,type:str]
    GITHUB_PROJECT_NUMBER: ENC[AES256_GCM,data:LA==,iv:1iClAbjbMrn2vlpcMV3iSeyG9savw69owVdWxtOs5kM=,tag:ZhBjslwLNHbo9Vhs9TXjXw==,type:str]
    GITHUB_REPO: ENC[AES256_GCM,data:d8J/Sf25olzrL1xprN76gmPv0gTQ8hJGsv8F6bgcN31xcxCUqo7tgb5+DBl3,iv:/0hU7O4V+UWrbPrDKRGHyGH7wjR8gN4MgsF18ZvY/gI=,tag:UG13RfSGa2XfJSZx1uHUrA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:/mwAkTBubB4VzGfiSYoLnJMuZg2jMB4YeMFIrXlR0Aa5HSwJEyM15A==,iv:GF4yzmPv+42uaoSGJhmxU7P9Xeoe0izsv0O7cX5W9sM=,tag:QWzTFEEbARjXDw7Bg+9hnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMFdyK2F6bWMrWnRhc3Vo
            Tnc1NzB0Q3RIa3AyMWw0QXpSQXNwcmZMYnlnCkdIN2xUV3ZSc1F5cjMvbnJjc2hx
            Sk1HTFowblg2SGY3cjhVWEZ0Zi9HS28KLS0tIFpyUmgrOWJsWmJaMkxSOUlEQ01m
            YXpCaDRIdkxMMjgxN0VmV0x0VE0rOXMKDBruK1Ee6XkDZZ0psiboH4BkzmjqB5m1
            3Ifpo0x7+DNAWebPO2ds1sZEtlBq0iqNh/CHcSphHYjulAud04rhJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T22:29:28Z"
    mac: ENC[AES256_GCM,data:+lxQklderVSz8TIB5P78i/Cd9YH9T2cmrBzC1AS9wYlMMunQc4Xyj005huAD6NqPkAaFLC834eCdSIkUp3YrExkt9EsREykGu4uo3xADJ7ZuY+/K+s4xJGGYEL/OsvXvSn4xPYqUFgj2mR2TyOI8acUbmkv4LucY3zqigJ/RflA=,iv:peUHI5AZAgkBARIS/rR98xLjGy8QLdEt/imHnANepZQ=,tag:9UnumGcCdht475MIpJUGkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
