apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: overseerr-manual
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /persistentdata/overseerr-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - funnyserver
