apiVersion: v1
kind: Secret
metadata:
    name: mobilitysoft-app-secrets
    namespace: prod
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:7R2qzid5WSQ=,iv:flWFbi/UMf11yb7Efk7IWvo7bUekjN1zsORb7CoTHTs=,tag:P3U3EoW9R1/zgm0KA7WAGQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:laKp+g==,iv:o44xBJ3qGMRPDt6RRiWR33ijQAqB8+GLNw5x11xG0mw=,tag:zOD6+nEhIvqY4Fc40igbwA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:9thgSDSs,iv:eHj8PjiGms+pWtws//mrpA6bcf8DMP98Zy3YlC9TOOw=,tag:trJMZuD50eASrkLwIwXfcA==,type:str]
    DB_USER: ENC[AES256_GCM,data:vww1QzI32N7PRg0=,iv:uetaItFwAcBhRs1twSMNxbYMnUwz9R08INSFnTIs9iU=,tag:QwzwTYSat21Qukj7NQF4qg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:FJuq4DgvZwQ0VwXWBYjj3dMM,iv:PyvUG0aetxuC2UyzqmhJLMdXUm+v1rMg92cpMT6+Y6c=,tag:2u5JSJnWRKbjcLJwGmvEVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYStZUEppOExKbW1qOFJB
            cUxUUHpiOW9qWmxRNXkwWWVFcEFKRWVIVFJBCkd6ZlNMdHhFOFRYNjJqQUhaTHJ1
            QWNrOFpoelZDSEJXQ0dVa3RaNjIrUE0KLS0tIFdoa2lJNXNpR2xteWRTV3NBdHNQ
            WmF2N3pPTm82YkJMR3dPUVhJTVpUcmMKPPUdiLdLNaeDuA/KW8F1R1vxEoUvfjg3
            vqLzzhs7zrQz6+JaPLZFp7NREvrH38+Qd93RG2rThAzr7ypmJz0zug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T03:54:41Z"
    mac: ENC[AES256_GCM,data:xHivNYkWkWIEPQWIv3H1DzvOWhgbqnAGyUvOgt/cYsjWR4WGqID5+KF9zjvMtDATdjL1HBeyAckFaqiEneCPEYphQ/pUJ9BChfP4WNlGxfnFw0fhcSZNf0kDW52Z+OtZVD8bMxVD1aOMmZFP2EJyHGJELwl2RJnVUuH7JMQQ7VM=,iv:rZXIKbaTP8Ykz+xQggoT52IeK0CsqnHpnX7LLnZHVK8=,tag:PiVhleZFS5Kv+yHXAeH4vQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
