apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
  - ./secrets/app-secrets.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
