apiVersion: v1
kind: Secret
metadata:
    name: metrics-app-secrets
    namespace: prod
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:RhpEzZiHft0=,iv:5l9RjVByEGpC7q7yzueiJHdIsoKUtirQxpOpxFuPw9Y=,tag:CTlvsYBxyTP1kZQisLupRg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:HocEgsFK,iv:EHRJ0ZSMerJsgZgd5xiPiFD7iz80c9OlPLTUKIKHsn8=,tag:LkwSm34v6PX21pzSGo10NA==,type:str]
    DB_USER: ENC[AES256_GCM,data:T82Ivt75O9wMJ+w=,iv:D+ciFVE6RDG6wx/tgH9lrYpLE+AfOQP55hLEJE+0Wnk=,tag:qOB2d7r8AOdzB6Un2NDN+Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:RLShBIggBcdn+uiS8Gl2t7vP,iv:Tnn+7P7mPWYKgp3fSX8MS9oK38UvpNu/r5pUFBajn4U=,tag:xdqiUdRukecuYI4uRC8dHw==,type:str]
    PORT: ENC[AES256_GCM,data:pcBCog==,iv:7HFwCldezHWVZGfBLZpPRIYLHkByQ1mkidhs0QcUJo4=,tag:TNc+qXhdI5ArnDFRZtookw==,type:str]
    GITHUB_PROJECT_NUMBER: ENC[AES256_GCM,data:3g==,iv:NfuQTo1Fqxourb8bumbAqYwZ4x60RQ25IddoHMvCajU=,tag:8+8Gwk/TOqJuEH/OWh7mNw==,type:str]
    GITHUB_REPO: ENC[AES256_GCM,data:SwUq42c5afvxsJ2N7hyMj5qyxqoyB071AI/Eh+QDSe9Jyjq6HMfXJvf2pSkr,iv:t9WT+vwrWL9yrF/ul4y0+46SVLb82aGXdDOkg3xBgaY=,tag:owEwHZc2Q8x5i4a1oSR7tw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:NIAx3JOKZA80ca7SS8cn9oAxjuBhFbor6t37SeMnU38DgGdXIaTYeg==,iv:xzA7c52NAHRhn+gr8rQAWeSr0x7pmQ/vm23Q3P7htFw=,tag:KDxWFReyamr1AH1itcnQOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUDhIUjRFZ1BTUlRWdXJk
            Y2E5SHJobGQ4RnR3cmg2b3pOZjdNWktvczFrCk96ZVJMM0svQ1dtL3ozRkg3WlVC
            bG1yenFRU0NDUTd5MlAwOTMvcXZFNmsKLS0tIHF3SWdOSHovNEx2dWZ3UEpZcGx1
            UUh5c3IyT05ubHRXRmlZdHczaU4wTDAKO6UpcCtTj1reERQZYnRgNQigwxHRJ9jI
            TDQSKnbLqJVOpd8uGjnN9RRJRwAJ0ztI0F9BA2Xe5FtPtfiuwdi2EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T04:37:25Z"
    mac: ENC[AES256_GCM,data:nq2ofZgVJ7r39dxw//EwpIylWf8rycYbJxWh1s2oKTuz1YHGROcFOa0K5RGczM47Y/0AQ/HYj7gbHmlOyUtVJADePzxXq/TMRxaOygbqcGqY1sW3GsdZ03ftP16aNQqsIMapDZO6K7s/1qgAyTg5+ruUIyfdjtjx3xdhT/+U2zg=,iv:k6GowgBRhP4lJZ2Y8de/Cs8nNuAP7G6iFDwyfZrpmZo=,tag:6PZzaXLB1D4s9qIRMieUuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
