apiVersion: ENC[AES256_GCM,data:o+I=,iv:eJIxZsezDpgEdJbXc2Ch3FbKmBuHyMaBxuhzFkZKaYw=,tag:w9tepjVDsr81+XxE7g2wWQ==,type:str]
kind: ENC[AES256_GCM,data:k2Z88tTa,iv:x+dfzUDQa74OItDsQQMqQXKhvmHt6iwfHtGWRynlNB8=,tag:zziBDyqTSrdF88JTtCrP+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RscC5qSars6Ykpg=,iv:8CHMzh1NexykXA59Cn5OyvCph2lbcgtLqj182s2zBTg=,tag:zEveqKYKI8HMhwuOwBu9AA==,type:str]
    namespace: ENC[AES256_GCM,data:7qqFZ+uL1A==,iv:vpYwbf7NCPTHtJi847ThmWvorGaw+VC1YFqC7UsR4YI=,tag:L5TTyC/5M54+Lgv+C4P+JA==,type:str]
type: ENC[AES256_GCM,data:QJZVpMCa,iv:Eoqobgf1kcbpkL5H/KI69aw4P69ayC4ZEdLnr8khwko=,tag:/2tlp30zoSiiQsl8SencZA==,type:str]
stringData:
    DB_HOST: ENC[AES256_GCM,data:s+PPT/tikyMU/A==,iv:u/lHS4txiYQPRqIFrBWpG6Uvgpoxr2/BhxjAif49B1w=,tag:dc0MdPlU1LgwgssQHiFkJg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:ZkOnmtdZ2rquDw==,iv:utgZ7MZ80kG2tNfzN6h6o5LtX5hPeBavJjKARAjF2co=,tag:f5a+KVl0uCNTJbZozW7efg==,type:str]
    DB_USER: ENC[AES256_GCM,data:5CFVdRtlsNfkeg==,iv:aWw/9jsqUi7i6w4KmjxW24PYrMxCkw7YbVl1sbXku2c=,tag:HG4C85HpXzvlrASs2jQjsg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:InFNM0pH57rnMRTWZgo=,iv:8k8T8azx11XmFuyBZY6vT2iA6XVADw4JvgzhJK1eQ9w=,tag:YaO5vbhCJPwwswr9Sv6lww==,type:str]
    API_PORT: ENC[AES256_GCM,data:tGPtO/naHNjT8gI=,iv:BCQpz/te6i06qRuBPLCpT1QPL6limiFIVTrW8Gakh6E=,tag:FbG+Jmm0zl6ZYlDpeJKrYw==,type:str]
    GITHUB_PROJECT_NUMBER: ENC[AES256_GCM,data:pNShN6lFrn2rPKb6ZtYm5cuR4h27tBzs,iv:mrlb5fv6yCqepXA+9qjaVWURYFnJ1PjyRzwse926tDg=,tag:vf1O/AoA2jf/f7Mv3xQe8A==,type:str]
    GITHUB_REPO: ENC[AES256_GCM,data:2W2NsMIG33J0i0vhtKk=,iv:P5qwdPRWcdw04/57wbCZ14peuSYGrPitp71PYJn+cgU=,tag:xX98zzG/GbGwZDJsqH9nPg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:uSoEXbtSxeQaaz/H790v,iv:Hl7BN2K1G3+BbMpe3geZrRFFrQCjfUvaOaHu+FSYGis=,tag:/aEbcSSgDX8zlzrw6XpGKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RStMM3dSdWJwOVNVa0sx
            MXRPRW5SRGk4eFk2UUFXaDlTQWJ6bHg4T25ZCmJtSVVjb3MwV3hnV1lJbllrWjE0
            aWQ4N0VaVUo4cXE3SGUvdk8xUGdDY1UKLS0tIC9pNGcwbXhaUmZoZ2lvTUlqN0NQ
            N0ZSRE4ydndKUnlEaDM2MXgzRytpZHMK3z4KM+FXU4CYlQRuy76o2q06CDLUEs5o
            A7Iirz5j2MCF1eSwbL0U8ujZ8yZNELonJheAsmZbTlRp+ICDdHA2ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-02T05:18:38Z"
    mac: ENC[AES256_GCM,data:EfeftE0VIsGPiQzzquFVqn4x7gVcu+xOW1H44BN4EzeIEj2ePLpUXL7peRv38L8UvyqvmbnHG91i+gfuUzxygoxMZYpQGo/NlN0z7syJFMjf74E2nqHhOT/IAUXH6bxklonkjjNol0L75uhU8GZ6GDAl9yOwoxDqY3bfDIiE544=,iv:kjb0gnZ6519rrNWacz8QOkl5gq7RgdtsoFD/t4LjR6c=,tag:qq0ZgKnMXMpxJ1FjZXO2lQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
