apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: staging
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:KjRmtC7Yfro=,iv:JTAheM8qbr3iB8duKU3hCw6mKfUVoi1VKKHrjYFzeNc=,tag:DpnW6rqxocWYm10zCrMXwQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Vu8ofiGc,iv:wTE+lF4gtEeLMFFEqjQacE0TbwsUEcoDguXwCCG6pUk=,tag:Uj2rbeb2zr0hJs7CtvyBlw==,type:str]
    DB_USER: ENC[AES256_GCM,data:pp7GhjZSi+dWO3E=,iv:5k7EdPsdD6Jx9AY5q1xX/hDoGvgdpB90h7iyRENj0Y0=,tag:gUOfVgYxfB/OLifvNSeC6g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:TQLyenGesrBj2IGAdEfRe1UH,iv:J7Sy1uum/cLOdA7cTYqDscHnFppw2WAZtuM3dUWa7sI=,tag:5I2+kuvFD4TPDkfPyWK/DQ==,type:str]
    PORT: ENC[AES256_GCM,data:ql2Itg==,iv:UFAk+rjTFGKb5HRgvprYPBe6DzQ/JTgCkpat3LaP7YI=,tag:dGjlwD/3PR+zQa7jOE8XSg==,type:str]
    GITHUB_PROJECT_NUMBER: ENC[AES256_GCM,data:DQ==,iv:OBgwl7vBVDGY7vra9lkd8jKyVoTmL31lNcwiuyZiOM0=,tag:AI2MBL7hJNxVkx25d+5MEQ==,type:str]
    GITHUB_REPO: ENC[AES256_GCM,data:ZzjcaC7lAkv916eX6tC4X0lgCcF18AROfHu0AjWw7boqoPOQ5B4HxjaaDTi+,iv:TtXVcpvc4+IRJA0Uwsl1tgxiL2/vfSErsbOsGC7tF1k=,tag:N35PI8t5aA9rRx4byN0nyA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:e9fqr6F9CQgHnoZSYs+yt/PGs2NZlcD2iw4B9YjCaMyqMjkhOUxJAA==,iv:s+7RJWGRL8Qx5vdrSIftjf5MKthHoaesbtIkDCNK5fI=,tag:Dz54vuty3ziJnOilsNH+jA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySkQ3MGFEcitMZFZXSDlK
            TkxZUzVjUkJaWWFBZlA3dk1SZUozdDIwR2djCk1IM21DbVlpVUhtdUk3RkZpQ1l1
            YnRXd1czZ2piYW96MUdqcjh5Smxvb1UKLS0tIGdlb3hOVmgrZ0R5MjlSSWVwYnlo
            U1FwSWNjWERzS0lmeW5IVUtTK3pScG8Ku9LcphNjyIO2TGv3lnyXAwbh0UkT+x7Y
            q5xxJTEpQrlMEyM60sSgcsemF/IIgXIQ7O/UMO6tCEtMOdebr7cURA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T19:01:50Z"
    mac: ENC[AES256_GCM,data:UGsoiQ2a/ovil5IYVx44DuVCzw7zz/4PBdBOclNEeCwANVCgQsGR1E+BZ9kojpoJdbSAOdAOYKGNw5wH3pB2Z0HPq5U4+o57Ag0WjZRistNDEE/3ju85BU1ONAn+QZ58fmffIlHHg0OciqYkWkjZDG6L+1hX/Nq2xOpl3Z5luMM=,iv:uUCNh1kH+WgD1/TpCEUdPNHCxKvT46Yk1q/oJic/yaU=,tag:QsYgVwnbVAa8V0m/ya/c1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
