apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  interval: 30m
  chart:
    spec:
      chart: gitops-server
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: weave-gitops
      interval: 12h
  values:
    service:
      type: ClusterIP
      port: 9001
    adminUser:
      create: true
      createSecret: false
      createClusterRole: true
      username: "admin"
      passwordHashSecret:
        name: weave-gitops-admin
        key: passwordHash
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: weave.home.adammihajlovic.ca
          paths:
            - path: /
              pathType: Prefix
