apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-admin
    namespace: weave-gitops
type: Opaque
stringData:
    passwordHash: ENC[AES256_GCM,data:q6VfU5JzbcGnehapiSFGBym2F5B7sX13WXEJVu8ZPOhzyaZ6SuhKjX3KpBI/ENSvy6yR0aY0yagC9aUI,iv:6jqubKKQzZdYU3cItoJsIxvdxru4zPsM6HwIf+nolEc=,tag:vgGdXPgRBCPiCum1Rs5LBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng7svucv0gjna8xu8v53krpfm0ekpyxqph8lsf2l2gss2j4kaevs57jwxs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjamRFTXpsVWk3cGdhZFRZ
            aWg1ZzJ3RzlGa1QrTTMrMXdGak8wclpIRFRNCjkyRGp2cVkzck0ya281TW9HMlFy
            RGZLNXo5aUViaFYrVWRRT0k0b2xhMm8KLS0tIFBVSC9NemNvMzZVWU5oYTlGWk1r
            cG1WekVYRkFJQk5zSW01WDdvZC9Jd3MKnfBJlGV1zohqfVoLfsWyJKJ9/MmxWIVz
            S5u9Am46jdq2FuWsDMICZUOnFU+8anXArkl3XMpd/v7W3q82Q3HFXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T21:39:58Z"
    mac: ENC[AES256_GCM,data:QlgT1nHKXolVi1ui1LNXZ8E19yyvjB0DEo+6B9xOcNavBQaWb8/tD1abuU46QAaUbJo9mZFgncMU57PZbgHdC4Vccf8lrsdob6+hQ4oQiap2SX1GnSlxeJuomjzyrGXyL274WXbrQ79tmS+d1ExwR83lQQKT0twRciMQiPiRZHM=,iv:t7k3puMyO0/01pINvYCT48F5dkJ9hdUDMWDl5XzlSxM=,tag:oKcWBAAco79NQfqzROLwQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
