apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  labels:
    app: seerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: seerr
          # image: ghcr.io/seerr-team/seerr:v3.2.0 # {"$imagepolicy": "flux-system:seerr-prod"}
          image: ghcr.io/seerr-team/seerr:v3.1.0
          ports:
            - containerPort: 5055
              name: http
          env:
            - name: TZ
              value: "America/Toronto"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: overseerr-persistent-volume-claim
