apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patches:
  - path: patch-images.yaml
  - path: patch-secrets.yaml
  - path: patch-ingress.yaml
