apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: overlays-staging
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: '[FluxCD Bot]: bump images staging'
    push:
      branch: main
  update:
    path: ./apps/log680/overlays/staging/patch-deployment.yaml
    strategy: Setters
