apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: overseerr-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: overseerr
  policy:
    semver:
      range: "*"
