apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata: { name: metrics-prod, namespace: flux-system }
spec:
  imageRepositoryRef: { name: metrics }
  filterTags:
    pattern: '^prod-(?P<ts>\d{14})-[0-9a-f]{7,40}$'
    extract: '$ts'
  policy:
    numerical: { order: asc }
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata: { name: mobilitysoft-prod, namespace: flux-system }
spec:
  imageRepositoryRef: { name: mobilitysoft }
  filterTags:
    pattern: '^prod-(?P<ts>\d{14})-[0-9a-f]{7,40}$'
    extract: '$ts'
  policy:
    numerical: { order: asc }
