apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata: { name: metrics-staging, namespace: flux-system }
spec:
  imageRepositoryRef: { name: metrics }
  filterTags:
    pattern: '^staging-(?P<ts>\d{8}-\d{6})-[a-f0-9]{7}$'
    extract: '$ts'
  policy:
    alphabetical: { order: asc }
---
# apiVersion: image.toolkit.fluxcd.io/v1
# kind: ImagePolicy
# metadata: { name: mobilitysoft-staging, namespace: flux-system }
# spec:
#   imageRepositoryRef: { name: mobilitysoft }
#   filterTags:
# filterTags:
#     pattern: '^staging-(?P<ts>\d{8}-\d{6})-[a-f0-9]{7}$'
#     extract: '$ts'
#   policy:
#     alphabetical: { order: asc }
