name: Publish Secrets to Infra (SOPS)
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/publish-secrets.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      INFRA_REPO: funnyadd/infra                 # <-- change to your infra repo
      INFRA_BRANCH: main                         # <-- target branch in infra repo
      APP_PATH: clusters/home/apps/metrics-a25-grp1-eq10  # <-- where app lives in infra
      STAGE_NS: staging
      PROD_NS: prod
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.INFRA_REPO }}
          ref: ${{ env.INFRA_BRANCH }}
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: infra

      - name: Install sops
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sops

      - name: Configure SOPS (age key)
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          mkdir -p ~/.config/sops/age
          printf '%s\n' "$SOPS_AGE_KEY" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt

      # Bring app secrets from GH → env
      - name: Load app secrets (staging)
        env:
          API_KEY: ${{ secrets.API_KEY_STAGING }}
          DB_URL:  ${{ secrets.DB_URL_STAGING }}
        run: |
          mkdir -p "infra/${APP_PATH}/${STAGE_NS}/secrets"
          cat > "infra/${APP_PATH}/${STAGE_NS}/secrets/app-secrets.yaml" <<'YAML'
          apiVersion: v1
          kind: Secret
          metadata:
            name: app-secrets
            namespace: ${STAGE_NS}
          type: Opaque
          stringData:
            API_KEY: "__API_KEY__"
            DB_URL: "__DB_URL__"
          YAML
          sed -i "s|__API_KEY__|${API_KEY}|g" "infra/${APP_PATH}/${STAGE_NS}/secrets/app-secrets.yaml"
          sed -i "s|__DB_URL__|${DB_URL}|g"   "infra/${APP_PATH}/${STAGE_NS}/secrets/app-secrets.yaml"
          sops -e -i "infra/${APP_PATH}/${STAGE_NS}/secrets/app-secrets.yaml"

      - name: Load app secrets (prod)
        if: ${{ github.ref == 'refs/heads/main' }}  # example guard; adjust as you like
        env:
          API_KEY: ${{ secrets.API_KEY_PROD }}
          DB_URL:  ${{ secrets.DB_URL_PROD }}
        run: |
          mkdir -p "infra/${APP_PATH}/${PROD_NS}/secrets"
          cat > "infra/${APP_PATH}/${PROD_NS}/secrets/app-secrets.yaml" <<'YAML'
          apiVersion: v1
          kind: Secret
          metadata:
            name: app-secrets
            namespace: ${PROD_NS}
          type: Opaque
          stringData:
            API_KEY: "__API_KEY__"
            DB_URL: "__DB_URL__"
          YAML
          sed -i "s|__API_KEY__|${API_KEY}|g" "infra/${APP_PATH}/${PROD_NS}/secrets/app-secrets.yaml"
          sed -i "s|__DB_URL__|${DB_URL}|g"   "infra/${APP_PATH}/${PROD_NS}/secrets/app-secrets.yaml"
          sops -e -i "infra/${APP_PATH}/${PROD_NS}/secrets/app-secrets.yaml"

      - name: Commit + push (direct)
        working-directory: infra
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore(secrets): update app-secrets for staging/prod"
            git push origin "${{ env.INFRA_BRANCH }}"
          fi