name: Render from Compose

on:
  push:
    paths: [ "docker-compose.yml", "kompose.yaml" ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.34.0/kompose-linux-amd64 -o /usr/local/bin/kompose
          chmod +x /usr/local/bin/kompose
      - name: Render base
        run: make render
      - name: Commit updated base (if changed)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add k8s/base
            git commit -m "chore: render base from docker-compose"
            git push
          fi
